// Runtime Config Types
declare module 'nuxt/schema' {
  interface RuntimeConfig {
    // Private keys
  }
  
  interface PublicRuntimeConfig {
    apiUrl: string
    wsUrl: string
    appName: string
    appVersion: string
    stripePublishableKey: string
  }
}

// This file is auto-generated by Nuxt
export {}